config/routes.rb
Rails.application.routes.draw do
  # GET / ⇒ houses#index
  root to: "houses#index"

  resources "houses", only: %i[index show]
  # GET /houses => houses#index
  # GET /houses/:id => houses#show

  resources "students", only: [:index, :show]
  # GET /students     => students#index
  # GET /students/:id => students#show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
  has_many :students

  validates :name, :points, presence: true
  validates :points, numericality: { only_integer: true }
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :house # One to many association

  validates :name, presence: true
  # The FK is also required (implicit validation)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  # GET /
  def index
    @houses = House.all
  end
  # Rails automatically loads the associated view:
  # app/views/houses/index.html.erb
  # All @houses variable is shared with the view

  # GET /houses/:id
  def show
    @house = House.find(params[:id])
  end
  # Rails automatically loads the associated view:
  # app/views/houses/show.html.erb
  # The @house variable are shared with the view
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  def index
    # The .includes removes our N+1 issue when
    # accessing the student houses in a loop in the view.
    @students = Student.includes(:house).order(:name)
  end
  # Automagically loads the associated view:
  # app/views/students/index.html.erb

  # GET /students/:id   => params[:id]
  def show
    @student = Student.find(params[:id])
  end
  # Automagically loads the associated view:
  # app/views/students/show.html.erb
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/houses/index.html.erb
<% if @houses.empty? %>
  <p>There are no houses available.</p>
<% else %>
  <% @houses.each do |house| %>
    <h2><%= house.name %> </h2>
    <p>
      There are <%= house.students.count %>
      students in this house.
    </p>
    <p>
      The students of this house have accumulated
      <%= house.points %> points.
    </p>
    <p>
      Learn more about house <%= link_to "house #{house.name}", house %>
    </p>
  <% end %>
<% end %>

app/views/houses/show.html.erb
<h2><%= @house.name %></h2>
<p>
  There are <%= @house.students.count %>
  students in this house.
</p>
<p>
  The students of this house have accumulated
  <%= @house.points %> points.
</p>

<h3>Students in house <%= @house.name %></h3>
<% if @house.students.empty? %>
  <p>There are no students in this house.</p>
<% else %>
  <ul>
    <% @house.students.each do |student| %>
      <li><%= link_to student.name, student %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hogwarts School Web App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body></body>
    <div class="container">
      <header>
        <h1>Hogwarts School of Wizards and Witches</h1>
        <p>
          <%= link_to 'Home', root_path %> |
          <%= link_to 'Students', students_path %>
        </p>
      </header>
      <%= yield %>
      <footer>
        Copywrong Hogwarts 2023.
      </footer>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h2>All Students</h2>

<% if @students.empty? %>
  <p>There are no students in the school.</p>
<% else %>
  <ul>
    <% @students.each do |student| %>
      <li>
        <%= link_to student.name, student %> of house
        <%= link_to student.house.name, student.house %>.
      </li>
    <% end %>
  </ul>
<% end %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>
<p>
  This student belongs to house <%= @student.house.name %>.
</p>